### ISSUE TITLE
Error Could not load 

### ISSUE THREAD

**Issue by TheGamersBrew** [EverNife/PixelmonEconomyBridge#1]
Upon loading get this server thread error. Even thought i'm running CMI for the Vault dependency. 
`20.07 23:53:59 [Server] Server thread/ERROR Could not load 'plugins/PixelmonEconomyBridge-1.0.8.jar' in folder 'plugins'
20.07 23:53:59 [Server] INFO org.bukkit.plugin.UnknownDependencyException: Unknown dependency Vault. Please download and install Vault to run this plugin.
20.07 23:53:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:269) ~[arclight:arclight-1.16.5-1.0.23-daa3c8bb]
20.07 23:53:59 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:381) ~[arclight:arclight-1.16.5-1.0.23-daa3c8bb]
20.07 23:53:59 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.handler$bbe000$arclight$loadPlugins(DedicatedServerMixin.java:637) ~[?:?]
20.07 23:53:59 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?]
20.07 23:53:59 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?]
20.07 23:53:59 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
20.07 23:53:59 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]`

**Comment by EverNife** [comment]
Vault is a plugin. CMI is another.

You need both of them on the server.

_(I think CMI has its own Vault fork somewhere as well.)_

Do you have both of them on the plugins folder?

> In your case you will need:
  - EverNifeCore.jar
  - CMI.jar
  - Vault.jar
  - PixelmonEconomyBridge

**Comment by TheGamersBrew** [comment]
tried that now it wont even let me in the server.
`21.07 17:42:29 [PebbleHost] TheGamersBrew ran command Message of the Day
21.07 17:42:29 [Server] Server thread/ERROR Exception caught during firing event: null
21.07 17:42:29 [Server] INFO Index: 4
21.07 17:42:29 [Server] INFO Listeners:
21.07 17:42:29 [Server] Startup0: HIGHEST
21.07 17:42:29 [Server] Startup1: ASM: class com.pixelmonmod.pixelmon.storage.extras.PixelExtrasStorage onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup2: ASM: class com.pixelmonmod.pixelmon.storage.extras.PixelExtrasStorage onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup3: HIGH
21.07 17:42:29 [Server] Startup4: ASM: class com.pixelmonmod.pixelmon.listener.PixelmonPlayerTracker onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup5: NORMAL
21.07 17:42:29 [Server] Startup6: ASM: class com.pixelmonmod.pixelmon.listener.ZygardeCellsListener onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup7: ASM: class com.pixelmonmod.pixelmon.listener.ZygardeCellsListener onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup8: ASM: class com.pixelmonmod.pixelmon.listener.ZygardeCellsListener onPlayerLeave(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup9: ASM: class com.pixelmonmod.pixelmon.listener.ZygardeCellsListener onPlayerLeave(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup10: ASM: sereneseasons.handler.season.SeasonHandler@6292b358 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup11: ASM: net.minecraftforge.common.ForgeInternalHandler@208a96ed playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup12: ASM: journeymap.common.events.ForgeEvents@33094449 onPlayerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup13: ASM: com.pixelmonmod.pixelmon.api.storage.PixelmonStorageManager@75143a89 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup14: ASM: class com.pixelmonmod.pixelmon.listener.EntityPlayerExtension onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup15: ASM: com.pixelmonmod.pixelmon.quests.listeners.PlayerListeners@f62b0cc onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] Startup16: ASM: com.pixelmonmod.pixelmon.spawning.TrackingSpawnerCoordinator@50154c3f onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
21.07 17:42:29 [Server] INFO java.lang.NullPointerException
21.07 17:42:29 [Server] INFO at br.com.finalcraft.pixelmoneconomybridge.implementation.v1_16_5.vaultonly.VaultBankAccountManager_v1_16_5.getBankAccount(VaultBankAccountManager_v1_16_5.java:18)
21.07 17:42:29 [Server] INFO at com.pixelmonmod.pixelmon.api.economy.BankAccountManager.getBankAccount(BankAccountManager.java:60)
21.07 17:42:29 [Server] INFO at com.pixelmonmod.pixelmon.api.economy.BankAccountProxy.getBankAccount(BankAccountProxy.java:84)
21.07 17:42:29 [Server] INFO at com.pixelmonmod.pixelmon.listener.PixelmonPlayerTracker.onPlayerLogin(PixelmonPlayerTracker.java:80)
21.07 17:42:29 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_103_PixelmonPlayerTracker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
21.07 17:42:29 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
21.07 17:42:29 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
21.07 17:42:29 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
21.07 17:42:29 [Server] INFO at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
21.07 17:42:29 [Server] INFO at net.minecraft.server.management.PlayerList.func_72355_a(PlayerListMixin.java:232)
21.07 17:42:29 [Server] INFO at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandlerMixin.java:621)
21.07 17:42:29 [Server] INFO at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandlerMixin.java:65)
21.07 17:42:29 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManagerMixin.java:222)
21.07 17:42:29 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
21.07 17:42:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:865)
21.07 17:42:29 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291)
21.07 17:42:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787)
21.07 17:42:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899)
21.07 17:42:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
21.07 17:42:29 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:829)
21.07 17:42:29 [Server] Server thread/ Failed to handle packet for /98.228.159.10:58071
21.07 17:42:29 [Server] INFO java.lang.NullPointerException: null
21.07 17:42:29 [Server] INFO at br.com.finalcraft.pixelmoneconomybridge.implementation.v1_16_5.vaultonly.VaultBankAccountManager_v1_16_5.getBankAccount(VaultBankAccountManager_v1_16_5.java:18) ~[?:?]
21.07 17:42:29 [Server] INFO at com.pixelmonmod.pixelmon.api.economy.BankAccountManager.getBankAccount(BankAccountManager.java:60) ~[pixelmon:1.16.5-9.0.6]
21.07 17:42:29 [Server] INFO at com.pixelmonmod.pixelmon.api.economy.BankAccountProxy.getBankAccount(BankAccountProxy.java:84) ~[pixelmon:1.16.5-9.0.6]
21.07 17:42:29 [Server] INFO at com.pixelmonmod.pixelmon.listener.PixelmonPlayerTracker.onPlayerLogin(PixelmonPlayerTracker.java:80) ~[pixelmon:1.16.5-9.0.6]
21.07 17:42:29 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_103_PixelmonPlayerTracker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
21.07 17:42:29 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
21.07 17:42:29 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
21.07 17:42:29 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
21.07 17:42:29 [Server] INFO at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?]
21.07 17:42:29 [Server] INFO at net.minecraft.server.management.PlayerList.func_72355_a(PlayerListMixin.java:232) ~[?:?]
21.07 17:42:29 [Server] INFO at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandlerMixin.java:621) ~[?:?]
21.07 17:42:29 [Server] INFO at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandlerMixin.java:65) ~[?:?]
21.07 17:42:29 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManagerMixin.java:222) ~[?:?]
21.07 17:42:29 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
21.07 17:42:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:865) ~[?:?]
21.07 17:42:29 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?]
21.07 17:42:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?]
21.07 17:42:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?]
21.07 17:42:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
21.07 17:42:29 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]
21.07 17:42:29 [Server] Craft Scheduler Thread - 37/ Plugin PixelmonEconomyBridge v1.0.8 generated an exception while executing task 36
21.07 17:42:29 [Server] INFO java.lang.NullPointerException: null
21.07 17:42:29 [Server] INFO at br.com.finalcraft.evernifecore.integration.VaultIntegration.ecoGet(VaultIntegration.java:67) ~[?:?]
21.07 17:42:29 [Server] INFO at br.com.finalcraft.pixelmoneconomybridge.implementation.v1_16_5.vaultonly.VaultUpdaterThread_v1_16_5$1.run(VaultUpdaterThread_v1_16_5.java:33) ~[?:?]
21.07 17:42:29 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.23-daa3c8bb]
21.07 17:42:29 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [arclight:arclight-1.16.5-1.0.23-daa3c8bb]
21.07 17:42:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
21.07 17:42:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
21.07 17:42:29 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]
21.07 17:42:30 [Server] Craft Scheduler Thread - 37/ Plugin PixelmonEconomyBridge v1.0.8 generated an exception while executing task 36
21.07 17:42:30 [Server] INFO java.lang.NullPointerException: null
21.07 17:42:30 [Server] INFO at br.com.finalcraft.evernifecore.integration.VaultIntegration.ecoGet(VaultIntegration.java:67) ~[?:?]
21.07 17:42:30 [Server] INFO at br.com.finalcraft.pixelmoneconomybridge.implementation.v1_16_5.vaultonly.VaultUpdaterThread_v1_16_5$1.run(VaultUpdaterThread_v1_16_5.java:33) ~[?:?]
21.07 17:42:30 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.23-daa3c8bb]
21.07 17:42:30 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [arclight:arclight-1.16.5-1.0.23-daa3c8bb]
21.07 17:42:30 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
21.07 17:42:30 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
21.07 17:42:30 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]
21.07 17:42:30 [Disconnect] User TheGamersBrew has disconnected, reason: Internal server error
21.07 17:42:30 [Server] Server thread/INFO TheGamersBrew left the game`

**Comment by EverNife** [comment]
Please, paste the log on a proper tool, like https://mcpaste.com/

The **full log!**

**Comment by TheGamersBrew** [comment]
how much of the full log? the whole server start up or where it kicks me after full load up. Cause I read over it and didn't see any errors during server start up. Only errored when I tried to connect to server.

**Comment by EverNife** [comment]
The full log will help me understand your environment! I need that give a proper help.

If you have personal data that should not be shown on the full log, create another server without these plugins, reproduce the bug and than give me the full log.

**Comment by TheGamersBrew** [comment]
I'll get you full log later tonight. I'll just cut out personal data (IP ect). The Plugins i'm using are fairly basic set as still getting full set up ready. That said after removing the EverNifeCore.jar and Vault.jar and reloading the server it seems to work just fine again. (though the economy bridge still doesn't work.)

**Comment by EverNife** [comment]
For the PixelmonEconomyBridge to work you need:
- Obligatorily [EverNIfeCore]
- Obligatorily [Vault]
- Obligatorily [AnyEconomyPlugin, for example, "CMI"]

_But i will wait for the full log, you can send it to me on the Private on discord if you want._

Rather than removing the plugins from the log, i would prefer you to create a servers without theses plugins (like on your local computer). 

Anyway, Take your time :D
